"""Service layer for running the ADK root agent on Vertex AI/Gemini."""

import asyncio
import inspect
import logging
import os
import re
from collections.abc import AsyncIterator
from typing import Any
from uuid import uuid4

from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from backend.agents.orchestrator import create_root_agent
from backend.utils.monitoring import LangfuseMonitor
from utils.config import load_settings

logger = logging.getLogger(__name__)

RETRY_DELAY_PATTERN = re.compile(
    r"retry(?: in|Delay['\"]?:?)\s*([0-9]+(?:\.[0-9]+)?)s", re.IGNORECASE
)


class QuotaExceededError(RuntimeError):
    """Raised when the Gemini backend returns RESOURCE_EXHAUSTED."""

    def __init__(self, message: str, retry_after_seconds: float | None = None) -> None:
        super().__init__(message)
        self.retry_after_seconds = retry_after_seconds


class VertexLLMService:
    """Run the backend's ADK root agent behind a simple service interface."""

    def __init__(
        self,
        project: str | None = None,
        region: str | None = None,
        model_name: str | None = None,
    ) -> None:
        settings = load_settings()
        self.auth_method = settings.vertex_ai.auth_method
        self.project = project or settings.vertex_ai.project
        self.region = region or settings.vertex_ai.region
        self.google_api_key = self._resolve_google_api_key(settings)
        self.model_name = model_name or settings.adk.model_name
        self.app_name = settings.adk.app_name
        self.default_user_id = settings.adk.default_user_id
        self.monitor = LangfuseMonitor()
        self._runner: Any | None = None
        self._session_service: Any | None = None
        self._configure_google_auth()

    async def generate_async(
        self,
        prompt: str,
        *,
        user_id: str | None = None,
        session_id: str | None = None,
        context: dict[str, Any] | None = None,
    ) -> str:
        """Run the ADK root agent and return its final text response."""

        result = await self.generate_with_trace_async(
            prompt,
            user_id=user_id,
            session_id=session_id,
            context=context,
        )
        return result["answer"]

    async def generate_with_trace_async(
        self,
        prompt: str,
        *,
        user_id: str | None = None,
        session_id: str | None = None,
        context: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Run the ADK root agent and return answer plus agent trace metadata."""

        logger.info("Preparing ADK run prompt=%r", prompt[:120])
        runner = self._get_runner()
        session_service = self._session_service
        resolved_user_id = user_id or self.default_user_id
        resolved_session_id = session_id or str(uuid4())
        logger.info(
            "Using ADK session user_id=%s session_id=%s has_context=%s",
            resolved_user_id,
            resolved_session_id,
            bool(context),
        )

        await self._create_session(
            session_service=session_service,
            user_id=resolved_user_id,
            session_id=resolved_session_id,
            state=context or {},
        )

        with self.monitor.trace_agent_run(
            prompt=prompt,
            user_id=resolved_user_id,
            session_id=resolved_session_id,
            metadata={"has_context": bool(context)},
        ) as span:
            try:
                logger.info("Starting ADK runner app_name=%s", self.app_name)
                content = self._new_user_content(prompt)
                final_answer = ""
                agent_trace: list[str] = []
                final_agent = self.app_name
                async for event in self._run_agent(
                    runner=runner,
                    user_id=resolved_user_id,
                    session_id=resolved_session_id,
                    content=content,
                ):
                    author = getattr(event, "author", None)
                    if isinstance(author, str) and author and author != "user":
                        if not agent_trace or agent_trace[-1] != author:
                            agent_trace.append(author)
                    if (
                        event.is_final_response()
                        and event.content
                        and event.content.parts
                    ):
                        if isinstance(author, str) and author:
                            final_agent = author
                            logger.info(
                                "Final response generated by agent=%s", final_agent
                            )
                        final_answer = "".join(
                            part.text or "" for part in event.content.parts if part.text
                        ).strip()

                if not final_answer:
                    raise RuntimeError(
                        "ADK runner completed without a final text response."
                    )

                logger.info("ADK runner produced final answer=%r", final_answer[:120])
                logger.info("ADK agent trace=%s", agent_trace)
                span.update(output={"answer": final_answer})
            except Exception as exc:
                logger.exception("ADK runner failed: %s", exc)
                span.update(level="ERROR", status_message=str(exc))
                if self._is_quota_error(exc):
                    raise QuotaExceededError(
                        str(exc),
                        retry_after_seconds=self._extract_retry_after_seconds(str(exc)),
                    ) from exc
                raise

        return {
            "answer": final_answer,
            "final_agent": final_agent,
            "agent_trace": agent_trace,
        }

    def generate(self, prompt: str, **kwargs: Any) -> str:
        """Synchronous wrapper for scripts and tests outside an event loop."""

        return asyncio.run(self.generate_async(prompt, **kwargs))

    def _get_runner(self) -> Any:
        """Create and cache the ADK runner used for backend chat requests."""

        if self._runner is not None:
            logger.info("Reusing cached ADK runner app_name=%s", self.app_name)
            return self._runner

        logger.info(
            "Creating ADK runner app_name=%s model=%s region=%s",
            self.app_name,
            self.model_name,
            self.region,
        )
        self._session_service = InMemorySessionService()
        root_agent = create_root_agent(model=self.model_name)
        self._runner = Runner(
            agent=root_agent,
            app_name=self.app_name,
            session_service=self._session_service,
        )
        return self._runner

    def _configure_google_auth(self) -> None:
        """Configure auth for Gemini Developer API or Vertex AI based on settings."""

        if self.auth_method == "vertex_ai":
            if not self.project:
                logger.warning(
                    "Vertex AI auth selected but no project configured. "
                    "Set vertex_ai.project for auth_method=vertex_ai."
                )
                return
            os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "true"
            os.environ["GOOGLE_CLOUD_PROJECT"] = self.project
            os.environ["GOOGLE_CLOUD_LOCATION"] = self.region
            os.environ.pop("GOOGLE_API_KEY", None)
            os.environ.pop("GEMINI_API_KEY", None)
            logger.info(
                "Configured Vertex AI authentication project=%s region=%s",
                self.project,
                self.region,
            )
            return

        if self.google_api_key is not None:
            api_key = self.google_api_key
            os.environ["GOOGLE_API_KEY"] = api_key
            os.environ["GEMINI_API_KEY"] = api_key
            os.environ.pop("GOOGLE_GENAI_USE_VERTEXAI", None)
            os.environ.pop("GOOGLE_CLOUD_PROJECT", None)
            os.environ.pop("GOOGLE_CLOUD_LOCATION", None)
            logger.info("Configured Gemini Developer API authentication from API key")
            return

        logger.warning(
            "No Gemini API key configured for auth_method=%s. "
            "Set vertex_ai.google_api_key in config.yaml.",
            self.auth_method,
        )

    def _resolve_google_api_key(self, settings: Any) -> str | None:
        """Resolve the API key from the selected config environment."""

        if settings.vertex_ai.google_api_key is not None:
            return settings.vertex_ai.google_api_key.get_secret_value()

        return os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")

    def _is_quota_error(self, exc: Exception) -> bool:
        """Identify Gemini quota exhaustion errors from ADK/GenAI exceptions."""

        message = str(exc)
        return "RESOURCE_EXHAUSTED" in message or "429" in message

    def _extract_retry_after_seconds(self, message: str) -> float | None:
        """Extract retry delay seconds from the provider error message when present."""

        match = RETRY_DELAY_PATTERN.search(message)
        if match is None:
            return None
        return float(match.group(1))

    async def _create_session(
        self,
        *,
        session_service: Any,
        user_id: str,
        session_id: str,
        state: dict[str, Any],
    ) -> None:
        """Create an ADK session, supporting sync and async session services."""

        logger.info("Creating ADK session state_keys=%s", sorted((state or {}).keys()))
        created = session_service.create_session(
            app_name=self.app_name,
            user_id=user_id,
            session_id=session_id,
            state=state,
        )
        if inspect.isawaitable(created):
            await created

    def _new_user_content(self, prompt: str) -> Any:
        """Build a GenAI user content object from a raw prompt."""

        return types.Content(role="user", parts=[types.Part(text=prompt)])

    def _run_agent(
        self,
        *,
        runner: Any,
        user_id: str,
        session_id: str,
        content: Any,
    ) -> AsyncIterator[Any]:
        """Run the ADK agent and stream invocation events."""

        logger.info(
            "Invoking ADK runner.run_async user_id=%s session_id=%s",
            user_id,
            session_id,
        )
        return runner.run_async(
            user_id=user_id,
            session_id=session_id,
            new_message=content,
        )
